### ISSUE TITLE
Double Sound Playing in background

### ISSUE THREAD

**Issue by BabbarRaghav** [dedomil/thala-for-a-reason#1]
Step to reproduce issue :-

In input type 7 and hit check. You will get a sound of success
When sound is playing in background again hit check and double sound will be played in background

**Comment by xydv** [comment]
which browser are you using? I just tested on Chrome 120.0.6099.109 and Firefox 120.0.1, its working fine

**Comment by BabbarRaghav** [comment]
I tested that on Chrome 115.0.5790.114

**Comment by xydv** [comment]
can you share the screencast video of the issue? cause I couldn't replicate!

**Comment by BabbarRaghav** [comment]
PFA link of screencast video

https://drive.google.com/file/d/1XhFbj0m2ZmZ_kJv0JI_8zOnRgS2CFVdF/view?usp=sharing

**Comment by xydv** [comment]
got it! the issue was that I wasn't pausing the music when button was clicked the next time!, thanks!
